// <auto-generated />
using BankMore.Transferencia.Infrastructure.Persistence.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankMore.Transferencia.Infrastructure.Persistence.EFCore.Migrations
{
    [DbContext(typeof(TransferenciaDbContext))]
    partial class TransferenciaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("BankMore.Transferencia.Domain.Entities.Idempotencia", b =>
                {
                    b.Property<string>("Chave")
                        .HasMaxLength(37)
                        .HasColumnType("TEXT")
                        .HasColumnName("chave_idempotencia");

                    b.Property<string>("Requisicao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("requisicao");

                    b.Property<string>("Resultado")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("resultado");

                    b.HasKey("Chave");

                    b.ToTable("idempotencia", (string)null);
                });

            modelBuilder.Entity("BankMore.Transferencia.Domain.Entities.Transferencia", b =>
                {
                    b.Property<string>("IdTransferencia")
                        .HasMaxLength(37)
                        .HasColumnType("TEXT")
                        .HasColumnName("idtransferencia");

                    b.Property<long>("ContaDestino")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idcontacorrente_destino");

                    b.Property<string>("DataMovimentoUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("datamovimento");

                    b.Property<string>("IdContaOrigem")
                        .IsRequired()
                        .HasMaxLength(37)
                        .HasColumnType("TEXT")
                        .HasColumnName("idcontacorrente_origem");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor");

                    b.HasKey("IdTransferencia");

                    b.ToTable("transferencia", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
